spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
server:
  port: 8011

logging:
  file:
    name: logs/testproject.log
    path: testproject
  level:
    com.geppetto: info
  pattern:
    dateformat: "dd-MM-yyyy hh:mm:ss aa"



























